### ISSUE TITLE
Leverage new RN JS Navigation

### ISSUE THREAD

**Issue by tlvenn** [ohanhi/elm-native-ui#11]
Facebook is working on a revamp of the JS Navigator and the preview is available here: https://github.com/ericvicenti/navigation-rfc

@ohanhi I believe this would solve the major blocker with the current implementation of the Navigator.

**Comment by ohanhi** [comment]
Oh wow. I will have to look into this. Thank you very much, @tlvenn!

**Comment by tlvenn** [comment]
Well I am glad I could be of help and thank you, @paulyoung and @staltz for this awesome project !

**Comment by ohanhi** [comment]
Update: this is actually moving along nicely. `NavigationExperimental` is now in RN master branch, and there's some improvements to it already in progress: https://github.com/facebook/react-native/pull/5912

**Comment by mk** [comment]
We tried updating react native to the current master in order to leverage the new navigation in https://github.com/elm-native-ui/elm-native-ui/compare/master...mk:navigation-experimental but it seems changes to the require polyfill are currently breaking Elm. 

We had to move the `F2` etc functions of the generated `elm.js` up a level to get it to work, see https://github.com/elm-native-ui/elm-native-ui/commit/16db2a046e4a1529177b3aa3c1d54c0acc326d45

**Comment by ohanhi** [comment]
@mk Interestingly, the anonymous function has always been there and it works under RN 0.14. But now that I am trying to upgrade to 0.21.0-rc, I am facing the same issue as you did: `Can't find variable: F2`. So strange.

**Comment by kommen** [comment]
@ohanhi Yeah, I was really surprised by that as well. But what do you mean with "has always been there"? As far as I saw, the anonymous function in the processed version of `elm.js` gets wrapped one more time additionally after upgrading RN.

Sorry for just providing screenshots here, but I found these in my scrap notes when I was digging into the issue.

Before upgrading RN:
![screen shot 2016-02-09 at 17 26 26](https://cloud.githubusercontent.com/assets/258/13253331/d8d805b0-da3b-11e5-9293-d4b87c22e9d4.png)

After upgrading RN:
![screen shot 2016-02-09 at 17 26 16](https://cloud.githubusercontent.com/assets/258/13253334/e054e344-da3b-11e5-91fc-faebe5025eff.png)

This is from compiled `index.ios.bundle` which gets served from the react packager (prettified version).

**Comment by ohanhi** [comment]
@kommen Where did you get that twice-wrapped file from? I can't see double `(function() {` rows in the compiled elm.js or in DevTools.

Edit: this was further discussed on the Elm Slack.

**Comment by ohanhi** [comment]
The undefined functions issue was circumvented in https://github.com/elm-native-ui/elm-native-ui/pull/14
Our `master` is now using React Native 0.21.0-rc with https://github.com/elm-native-ui/elm-native-ui/pull/19

**Comment by ohanhi** [comment]
With #44 and #49, I'd say this is now done!
