### ISSUE TITLE
Really want to help, what can I start experimenting with?

### ISSUE THREAD

**Issue by stereokai** [ohanhi/elm-native-ui#13]
I'm excited about this, I really love working with Elm, but my React/React Native experience is limited.

How can I contribute?

**Comment by ohanhi** [comment]
Thanks for the support!

I am currently upgrading to React Native 0.21.0-rc, which has solid improvements on many fronts compared to the current master branch. Once that's done, I'll try to mold the app into a startappy structure. From then on, the road is pretty open, so I will keep you posted.

**Comment by stereokai** [comment]
Cheers. So, by then, I think I'll up my React Native & Redux fu, and hopefully, when that time arrives, I'll have something I can contribute. Anything in specific to focus on?

**Comment by ohanhi** [comment]
Well the new NavigationExperimental is the main thing I'm after with 0.21.0-rc. That doesn't exist in earlier releases. But I guess one easy way into this project would be just figuring out some of the commonly used RN components (such as `TouchableOpacity`), and providing the helper functions for those. Also, props (aside from styles) can't be passed to components as of now, so if you come up with an idea of how we could unify the all the different kinds of properties into one list somehow, that would be great.

I will open up some issues describing these things so we have a better idea of what's planned / being worked on.

**Comment by stereokai** [comment]
Nice. I'm on it. Expect some updates later on.

PS. watching the repo as well.
