### ISSUE TITLE
Allow the StyleSheet.create method for styles

### ISSUE THREAD

**Issue by ohanhi** [ohanhi/elm-native-ui#17]
`StyleSheet.create` is the preferred way of providing styles in React Native ([docs](https://facebook.github.io/react-native/docs/style.html#content)).

**Comment by sudhirvkumar** [comment]
@ohanhi I am working on this. Will let you know as soon as I have made some progress.

**Comment by Qata** [comment]
I'm guessing no progress has been made in the last year?

**Comment by ohanhi** [comment]
@Qata, yeah I think Sudhir has abandoned his endeavors here.

**Comment by gabrielperales** [comment]
I'm working on this, there is a  pull request and it seems to work properly but I have some design doubts I would like to discuss
