### ISSUE TITLE
Write a blog post about calling react-native from Elm

### ISSUE THREAD

**Issue by SekibOmazic** [ohanhi/elm-native-ui#2]
You saw this issue coming, didn't you :-)

**Comment by ohanhi** [comment]
@SekibOmazic 😄
This is the best possible issue for this repository at this point! Thank you, me and @staltz will write a post about this. Once that is done, I will close this issue with a link to the article.

**Comment by ryyppy** [comment]
This is really exciting! :+1:

**Comment by GTDev87** [comment]
Oh my god.  I want this to exist.  Make it so!  How can I contribute?

**Comment by zhangcheng** [comment]
+1

**Comment by thisredone** [comment]
:+1:

**Comment by doppioslash** [comment]
+1

**Comment by ohanhi** [comment]
Took my time, but here it is: [Elm Native UI: Writing a React Native app in Elm](http://ohanhi.github.io/elm-native-ui.html) :tada:

**Comment by SekibOmazic** [comment]
:+1:

**Comment by HughGrant** [comment]
great great job
