### ISSUE TITLE
Getting started instruction

### ISSUE THREAD

**Issue by hiaw** [ohanhi/elm-native-ui#36]
I was trying to get started and I was stuck on the app not running. After a bit of digging, I found that I need to give a different name than MyAppName for package.json, otherwise it would work. What happen is that elm-native-ui/example/package.json already took MyAppName and so compiler will fail.

Please add this bit of instruction to README.md
Edit package.js to give a different name. 

Thanks.

**Comment by ohanhi** [comment]
Interesting, thank you for this observation. So you're saying that using the same name in `package.json` as for the React Native project will make the app fail to launch?

**Comment by hiaw** [comment]
Yes.
