### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by sudhirvkumar** [ohanhi/elm-native-ui#37]
@ohanhi @eeue56 @mk 

As 0.17 Alpha has been released in elm-dev. What is the plan for Elm Native UI?

How can we collaborate?

Thank You!

**Comment by eeue56** [comment]
I've spent the morning getting familiar with the new way of doing Native stuff and also working with the new way elm-html works. Gonna need a few more days to think about this.

**Comment by sudhirvkumar** [comment]
@eeue56 Noah... I am waiting... :)

**Comment by sudhirvkumar** [comment]
I am closing this issue and will create separate issues for each idea / feature. We can continue our discussion in those issues.

**Comment by sudhirvkumar** [comment]
Will keep this open till we create a plan.

@eeue56 Noah, @ohanhi  Any update on the plan?

**Comment by ohanhi** [comment]
No, and I really don't think we need to rush it. I work full-time, and only do this as a hobby. As do all the other contributors, I presume. I, or anyone else, do not see it as our _duty_ to develop this project. We simply may decide to do so if/when we have time. So please, do not try and set milestones or deadlines for us. We are well capable of doing it ourselves should we want to. You are welcome to go ahead with your fork and handle the project any way you see best, of course.

**Comment by sudhirvkumar** [comment]
@ohanhi @eeue56 @mk 

I was neither setting a deadline nor milestones for any of you. Just wanted to know if you guys have any plans.
Thanks for the reply. I got what your plan for elm-native-ui is. You will work on it when you get some time. I respect that. 

For me this is full time job and I am employing people to work on this :)

I wont bother you guys anymore. I thought it would make sense to collaborate rather than compete on the same thing which is going to be Open Source anyway.

Once we make some progress I will ping you on twitter. Everyone is welcome to collaborate.

Thank you for being polite about it!
