### ISSUE TITLE
Logo idea

### ISSUE THREAD

**Issue by paulyoung** [ohanhi/elm-native-ui#5]
I made these in vector format if there's any interest in using them.

![elm-native-512](https://cloud.githubusercontent.com/assets/84700/11440614/05cd07da-94fc-11e5-8e7e-a55fe708191b.png)

![elm-native-blue-512](https://cloud.githubusercontent.com/assets/84700/11440603/f6afe0ba-94fb-11e5-894a-8c498ea7dab7.png)

**Comment by ohanhi** [comment]
Nicely done! We could also investigate whether it's feasible to use the pieces of the Elm tangram to convey the React atom.

**Comment by paulyoung** [comment]
> We could also investigate whether it's feasible to use the pieces of the Elm tangram to convey the React atom.

That's what I was going for :smile:

**Comment by ohanhi** [comment]
Well yeah.. :D
What I meant by that was "using only the 7 pieces of a single tangram puzzle".

**Comment by paulyoung** [comment]
I couldn't see an obvious way to make it work but can revisit.

**Comment by ohanhi** [comment]
@paulyoung Actually, just submit a PR with your first logo suggestion in place of the current one, and let's call it a day. It's really good-looking! :sparkling_heart:

**Comment by paulyoung** [comment]
I put this together for Dribbble, wanted to share.

![elm-native-dribbble](https://cloud.githubusercontent.com/assets/84700/11529687/a083238e-98e6-11e5-9519-8cde73bca9d2.png)

**Comment by ohanhi** [comment]
👍
