### ISSUE TITLE
Proposal to remove generator code

### ISSUE THREAD

**Issue by jsteiner** [ohanhi/elm-native-ui#53]
In [a recent commit](https://github.com/ohanhi/elm-native-ui/commit/2a40e869dec18585327b163bd9f20c2d3a15d18b), @jferris and myself ended up spending a majority of our time debugging and figuring out how the generators worked, so we could "write" a couple lines of Elm code. While the generators were meant to reduce time spent, they now seem like an impediment. For repetitive transformations of the Elm code, it seems like that could be done with a sufficiently advanced text editor.

If you agree, we'd be happy to make this change.

**Comment by ohanhi** [comment]
@jsteiner Yeah, I suppose that'd be okay. This project does not support (or even claim to) all of React Native's core anyway. If anything, having everything generated in there is miscommunication as it stands.
