### ISSUE TITLE
Suggestion: Use Exponent RN wrapper framework!?

### ISSUE THREAD

**Issue by kristianmandrup** [ohanhi/elm-native-ui#59]
Exponent is like Rails for React Native, makes it much, much easier to build an app on React Native!

https://getexponent.com/

https://docs.getexponent.com/versions/v12.0.0/index.html

https://www.youtube.com/watch?v=7lZtV-rIAmY

New project template (RN template with a few extras for exponent integration)
https://github.com/exponent/new-project-template

**Comment by ohanhi** [comment]
In the long run, the goal is to become less dependent on React Native as a platform, so it doesn't really make sense for us to put another level of depency on the current model.
