### ISSUE TITLE
Contribution Guide?

### ISSUE THREAD

**Issue by jonlaing** [ohanhi/elm-native-ui#70]
Hi, I'm very new to Elm, but I'd like to get into it. I'm a full-time JS dev though, and I'm a big fan of React Native. I'd love to contribute what little time I have to furthering this project, but I'm not exactly sure where/how to get started.

If there were a guide on what the preferred way to contribute was, that would be great. Also, is there a guide somewhere on how you're doing the Elm->JS interop like in the `src/Native` directory? My cursory google search didn't turn up anything like what I'm seeing in this repo.

Thanks!

**Comment by ohanhi** [comment]
Hi @jonlaing!

As much as I appreciate the enthusiasm, this is very much an experimental project, and as such it is definitely not the best place to get into Elm. Things may change rapidly, and much of the code is comparable to working on the core of Elm itself. There are many pure Elm projects needing helping hands, though -- those would be much nicer to work with!

The native code, in particular, is something _pretty much no one in the Elm community should write_. It is the most effective way to introduce runtime exceptions in your Elm programs, and all regular Elm users should use [ports](https://guide.elm-lang.org/interop/javascript.html) instead. This is why there is hardly any documentation on Native.

I hope I didn't come out as dismissive, and that all this makes sense to you. Good luck with your endeavors in Elm!

**Comment by kylebakerio** [comment]
Does that mean your official advice to anyone who isn't familiar with elm is to go get familiar with elm first before diving in here? (Just clarifying.)

**Comment by ohanhi** [comment]
Yes, that is precisely what I meant. :)
