### ISSUE TITLE
Swap order of arguments for ListView.updateDataSource

### ISSUE THREAD

**Issue by Janiczek** [ohanhi/elm-native-ui#71]
This seems like an idiomatic way to write the `updateDataSource`:

```elm
ListView.emptyDataSource
    |> ListView.updateDataSource [ 1, 2, 3 ]
```

but right now we can't do that - the data source has to be the first argument, so the best the user can currently do is to `flip` the function.

(This is similar to the `*.andThen` debate and BC change in `elm-lang/core` not so long ago).

**Comment by ohanhi** [comment]
Hi, I agree with your reasoning. The data operated on should be the last argument to the function. I'd be up for a PR on this, if you'd like to contribute!
