### ISSUE TITLE
[QUESTION] Having some trouble understanding the code

### ISSUE THREAD

**Issue by giulianok** [ohanhi/elm-native-ui#99]
I'm having a hard time trying to understand this here https://github.com/ohanhi/elm-native-ui/blob/master/src/NativeUi.elm#L69-L71 

where is `customNode` defined for example?

**Comment by ohanhi** [comment]
This is old Elm. Current versions don't have Native modules anymore. But anyway, it's a reference to the function here: https://github.com/ohanhi/elm-native-ui/blob/master/src/Native/NativeUi.js#L112
